# Generated by Django 3.2.7 on 2022-05-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment',
            new_name='Comments',
        ),
    ]
