# Generated by Django 3.2.7 on 2022-05-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Year', models.TextField(blank=True)),
                ('Rated', models.TextField(blank=True)),
                ('Released', models.TextField(blank=True)),
                ('Runtime', models.TextField(blank=True)),
                ('Genre', models.TextField(blank=True)),
                ('Director', models.TextField(blank=True)),
                ('Actors', models.TextField(blank=True)),
            ],
        ),
    ]
