# Generated by Django 3.2.7 on 2022-05-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Awards',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='BoxOffice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Country',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='DVD',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Language',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Metascore',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Plot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Poster',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Production',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Ratings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Website',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Writer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdbID',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdbRating',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdbVotes',
            field=models.TextField(blank=True),
        ),
    ]
