# Generated by Django 3.2.7 on 2022-05-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('movies', '0003_remove_movie_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='movies', to='comments.Comment'),
        ),
    ]
