# Generated by Django 3.2.7 on 2022-05-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_comments_movie_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Comment',
            new_name='Comments',
        ),
    ]
